name: task_list
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.3.2
  build_runner: ^2.4.5


flutter:

  uses-material-design: true

  assets:
      - assets/images/

  fonts:
      - family: Urbanist
        fonts:
        - asset: assets/fonts/urbanist.ttf
